### PR TITLE
Slim down the package

### PR DESCRIPTION
**Pull request by shinnn**
* I removed .npmignore. It's unnecessary since #6.
* I updated package.json.
  * remove unnecessary `main`
  * use [user/repo](https://github.com/npm/npm/issues/3783) style

### CODE REVIEW

**Comment by MatthewMueller** [comment]
thanks man

**Comment by shinnn** [comment]
@MatthewMueller No problem! I'd be glad if you release a new version :)

**Comment by MatthewMueller** [comment]
done!

**Comment by shinnn** [comment]
:+1:

**Pull request merged**
